package VISTA;

import MODELO.LoginDAO;
import MODELO.login;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {
    login lg = new login();
    LoginDAO loginDAO = new LoginDAO(); 

    public Login() {
        initComponents();
        this.setBounds(0, 0, 1350, 750);
        this.setLocationRelativeTo(null);
    }

    public void validar() {
        String usuario = Usuario.getText();
        String contraseña = String.valueOf(Contraseña.getPassword());
        if (!"".equals(usuario) && !"".equals(contraseña)) {
            lg = loginDAO.log(usuario, contraseña);
            if (lg.getUsuario() != null) {
                if ("3".equals(lg.getRol())) {
                    home_superadmin superAdminHome = new home_superadmin();
                    superAdminHome.setVisible(true);
                } else if ("2".equals(lg.getRol())) {
                    home_administrador adminHome = new home_administrador();
                    adminHome.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Acceso denegado: Rol no autorizado");
                    return;
                }
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrecta");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos.");
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Eliminar = new javax.swing.JButton();
        Iniciar = new javax.swing.JButton();
        Contraseña = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(144, 12, 63));
        setSize(new java.awt.Dimension(1350, 725));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel3.setText("GigaGains ADMIN");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(80, 50, 420, 67);

        Usuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(144, 12, 63), 3));
        Usuario.setSelectionColor(new java.awt.Color(0, 0, 0));
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(Usuario);
        Usuario.setBounds(110, 220, 370, 40);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setText("Usuario:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(110, 190, 80, 26);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setText("Contraseña:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(110, 310, 110, 26);

        Eliminar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Eliminar.setForeground(new java.awt.Color(144, 12, 63));
        Eliminar.setText("Salir");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPanel2.add(Eliminar);
        Eliminar.setBounds(170, 520, 240, 40);

        Iniciar.setBackground(new java.awt.Color(144, 12, 63));
        Iniciar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Iniciar.setForeground(new java.awt.Color(255, 255, 255));
        Iniciar.setText("Iniciar Sesion");
        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });
        jPanel2.add(Iniciar);
        Iniciar.setBounds(170, 460, 240, 40);

        Contraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(144, 12, 63), 3));
        Contraseña.setSelectionColor(new java.awt.Color(0, 0, 0));
        Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaActionPerformed(evt);
            }
        });
        jPanel2.add(Contraseña);
        Contraseña.setBounds(110, 340, 370, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(400, 10, 590, 660);

        jPanel1.setBackground(new java.awt.Color(144, 12, 63));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -30, 1350, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_EliminarActionPerformed

    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed
        validar();
    }//GEN-LAST:event_IniciarActionPerformed

    private void ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Contraseña;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Iniciar;
    private javax.swing.JTextField Usuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
