
package VISTA;

import MODELO.*;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class planes extends javax.swing.JFrame {
    
    Usuario us = new Usuario();
    UsuarioDAO user = new UsuarioDAO();
    PlanesVer pla = new PlanesVer();
    PlanesVerDAO plaDao = new PlanesVerDAO();
    DefaultTableModel modelo = new DefaultTableModel();
    
    public planes() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setBounds(0,0,650,460);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        llenarComboBoxNombresPlanes();
        inicializarEventos();
    }
    
    private void llenarComboBoxNombresPlanes() {
        List<String> nombres = user.obtenerNombresPlanes();
        comboxplanes.removeAllItems();  // Limpiar el JComboBox

        for (String nombre : nombres) {
            comboxplanes.addItem(nombre);  // Agregar cada nombre
        }
    }    
    private void inicializarEventos() {
        comboxplanes.addActionListener(e -> {
            String nombrePlanSeleccionado = (String) comboxplanes.getSelectedItem();
            if (nombrePlanSeleccionado != null) {
                actualizarTablaRutina(nombrePlanSeleccionado); 
                actualizarTablaDieta(nombrePlanSeleccionado);
            }
        });  
    }
    private void actualizarTablaRutina(String nombreRutina) {
        List<PlanesVer> listaRutinas = plaDao.obtenerRutinaPorPlan(nombreRutina);
        // Limpiar la tabla antes de agregar nuevos datos
        modelo = (DefaultTableModel) TableRutina.getModel();
        modelo.setRowCount(0);
        // Agregar filas con datos de los ejercicios
        for (PlanesVer rutina : listaRutinas) {
        Object[] fila = {
            rutina.getRutina_id(),
            rutina.getNombre_rutina()
        };
            modelo.addRow(fila);
        }
    }
    
    private void actualizarTablaDieta(String nombreDieta) {
        List<PlanesVer> listaRutinas = plaDao.obtenerDietaPorPlan(nombreDieta);
        // Limpiar la tabla antes de agregar nuevos datos
        modelo = (DefaultTableModel) TableDieta.getModel();
        modelo.setRowCount(0);
        // Agregar filas con datos de los ejercicios
        for (PlanesVer rutina : listaRutinas) {
        Object[] fila = {
            rutina.getDieta_id(),
            rutina.getTipo_dieta(),
            rutina.getProteinas(),
            rutina.getCarbohidratos(),
            rutina.getCalorias()
        };
            modelo.addRow(fila);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        TableRutina = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        TableCircuito2 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        TableCircuito3 = new javax.swing.JTable();
        jScrollPane11 = new javax.swing.JScrollPane();
        TableDieta = new javax.swing.JTable();
        comboxplanes = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(144, 12, 63));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PLAN SELECCIONADO");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Rutina:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        TableRutina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre"
            }
        ));
        TableRutina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableRutinaMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(TableRutina);
        if (TableRutina.getColumnModel().getColumnCount() > 0) {
            TableRutina.getColumnModel().getColumn(0).setMinWidth(100);
            TableRutina.getColumnModel().getColumn(0).setPreferredWidth(100);
            TableRutina.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jPanel2.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 620, 60));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Dieta:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Circuitos:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        TableCircuito2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre"
            }
        ));
        TableCircuito2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableCircuito2MouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(TableCircuito2);
        if (TableCircuito2.getColumnModel().getColumnCount() > 0) {
            TableCircuito2.getColumnModel().getColumn(0).setMinWidth(100);
            TableCircuito2.getColumnModel().getColumn(0).setPreferredWidth(100);
            TableCircuito2.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jPanel2.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 620, 80));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ejercicios:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        TableCircuito3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Series"
            }
        ));
        TableCircuito3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableCircuito3MouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(TableCircuito3);
        if (TableCircuito3.getColumnModel().getColumnCount() > 0) {
            TableCircuito3.getColumnModel().getColumn(0).setMinWidth(100);
            TableCircuito3.getColumnModel().getColumn(0).setPreferredWidth(100);
            TableCircuito3.getColumnModel().getColumn(0).setMaxWidth(100);
            TableCircuito3.getColumnModel().getColumn(2).setMinWidth(200);
            TableCircuito3.getColumnModel().getColumn(2).setPreferredWidth(200);
            TableCircuito3.getColumnModel().getColumn(2).setMaxWidth(200);
        }

        jPanel2.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 620, 80));

        TableDieta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tipo", "Proteinas", "Carbos", "Calorias"
            }
        ));
        TableDieta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDietaMouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(TableDieta);
        if (TableDieta.getColumnModel().getColumnCount() > 0) {
            TableDieta.getColumnModel().getColumn(0).setMinWidth(100);
            TableDieta.getColumnModel().getColumn(0).setPreferredWidth(100);
            TableDieta.getColumnModel().getColumn(0).setMaxWidth(100);
            TableDieta.getColumnModel().getColumn(2).setMinWidth(100);
            TableDieta.getColumnModel().getColumn(2).setPreferredWidth(100);
            TableDieta.getColumnModel().getColumn(2).setMaxWidth(100);
            TableDieta.getColumnModel().getColumn(3).setMinWidth(100);
            TableDieta.getColumnModel().getColumn(3).setPreferredWidth(100);
            TableDieta.getColumnModel().getColumn(3).setMaxWidth(100);
            TableDieta.getColumnModel().getColumn(4).setMinWidth(100);
            TableDieta.getColumnModel().getColumn(4).setPreferredWidth(100);
            TableDieta.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        jPanel2.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 620, 60));

        comboxplanes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboxplanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxplanesActionPerformed(evt);
            }
        });
        jPanel2.add(comboxplanes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 120, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableRutinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableRutinaMouseClicked

    }//GEN-LAST:event_TableRutinaMouseClicked

    private void TableCircuito2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableCircuito2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TableCircuito2MouseClicked

    private void TableCircuito3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableCircuito3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TableCircuito3MouseClicked

    private void TableDietaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDietaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TableDietaMouseClicked

    private void comboxplanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxplanesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxplanesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(planes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(planes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(planes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(planes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new planes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableCircuito2;
    private javax.swing.JTable TableCircuito3;
    private javax.swing.JTable TableDieta;
    private javax.swing.JTable TableRutina;
    private javax.swing.JComboBox<String> comboxplanes;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    // End of variables declaration//GEN-END:variables
}
