
package VISTA;

import MODELO.*;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 * Clase Progreso que representa la ventana de seguimiento de progreso de los usuarios.
 */
public class Progreso extends javax.swing.JFrame {
// Instancias de los modelos para manejar los datos de progreso
    progreso pro = new progreso();
    ProgresoDAO proDAO = new ProgresoDAO();
    DefaultTableModel modelo1 = new DefaultTableModel();
     /**
     * Constructor de la clase Progreso.
     * Configura la ventana y sus propiedades.
     */
    public Progreso() {
        initComponents(); // Inicializa los componentes gráficos
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Permite cerrar solo esta ventana sin afectar la aplicación
        this.setBounds(0, 0, 650, 460); // Define el tamaño de la ventana
        this.setLocationRelativeTo(null); // Centra la ventana en la pantalla
        this.setResizable(false); // Evita que la ventana sea redimensionada
        llenarComboBoxNombresUsuarios(); // Llena el ComboBox con los nombres de usuarios
        inicializarEventos(); // Inicializa los eventos
    }
    /**
     * Método para llenar el ComboBox con los nombres de los usuarios registrados.
     */
     private void llenarComboBoxNombresUsuarios() {
        List<String> nombres = proDAO.obtenerNombresUsuarios(); // Obtiene la lista de nombres de usuarios
        comboxusuario.removeAllItems(); // Limpia el ComboBox antes de agregar nuevos elementos

        for (String nombre : nombres) {
            comboxusuario.addItem(nombre); // Agrega cada nombre al ComboBox
        }
    } 
    /**
    * Método para inicializar los eventos del ComboBox.
    * Al seleccionar un usuario, se actualiza la tabla con su progreso.
    */
    private void inicializarEventos() {
        comboxusuario.addActionListener(e -> {
            String nombreUsuarioSeleccionado = (String) comboxusuario.getSelectedItem();
            if (nombreUsuarioSeleccionado != null) {
                LimpiarTable1(); // Limpia la tabla antes de cargar nuevos datos
                actualizarTablaUSUARIOS(nombreUsuarioSeleccionado); // Actualiza la tabla con la información del usuario seleccionado
            }
        });  
    }
    /**
     * Método para actualizar la tabla con el progreso del usuario seleccionado.
     * @param nombreUsuario Nombre del usuario del que se desea obtener el progreso.
     */
    private void actualizarTablaUSUARIOS(String nombreUsuario) {
        List<progreso> listaUsuario = proDAO.obtenerProgresoUsuarios(nombreUsuario); // Obtiene la lista de progresos
        modelo1 = (DefaultTableModel) TableRutina.getModel(); // Obtiene el modelo de la tabla
        modelo1.setRowCount(0); // Limpia la tabla antes de agregar nuevos datos
        // Agregar filas con datos de los ejercicios
        for (progreso rutina : listaUsuario) {
        Object[] fila = {
            rutina.getId(),
            rutina.getUsuario_id(),
            rutina.getPeso(),
            rutina.getFecha()
        };
            modelo1.addRow(fila);
        }
        
    }
    /**
     * Método para limpiar la tabla de progreso.
     */
    public void LimpiarTable1() {
        for (int i = 0; i < modelo1.getRowCount(); i++) {
            modelo1.removeRow(i);
            i = i - 1;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        TableRutina = new javax.swing.JTable();
        comboxusuario = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(144, 12, 63));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("USUARIO SELECCIONADO");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        TableRutina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Usuario_ID", "Peso", "Fecha"
            }
        ));
        TableRutina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableRutinaMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(TableRutina);
        if (TableRutina.getColumnModel().getColumnCount() > 0) {
            TableRutina.getColumnModel().getColumn(0).setMinWidth(100);
            TableRutina.getColumnModel().getColumn(0).setPreferredWidth(100);
            TableRutina.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jPanel2.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 620, 340));

        comboxusuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboxusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxusuarioActionPerformed(evt);
            }
        });
        jPanel2.add(comboxusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableRutinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableRutinaMouseClicked

    }//GEN-LAST:event_TableRutinaMouseClicked

    private void comboxusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxusuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Progreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Progreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Progreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Progreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Progreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableRutina;
    private javax.swing.JComboBox<String> comboxusuario;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane7;
    // End of variables declaration//GEN-END:variables
}
